### ISSUE TITLE
Error browsing back to mutations pane

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tsbrowse#182]
Worked fine first time, second time I went back to a stack trace

```
2024-09-30 10:34:46,883 ERROR: panel.reactive - Callback failed for object named "Select Page" changing property {'value': 'Mutations'}                                                       
Traceback (most recent call last):                                                                                                                                                            
  File "/home/jk/.local/lib/python3.10/site-packages/panel/reactive.py", line 384, in _process_events              

snip

    plot = self._render(doc, comm, root)
  File "/home/jk/.local/lib/python3.10/site-packages/panel/pane/holoviews.py", line 506, in _render
    return renderer.get_plot(self.object, **kwargs)
  File "/home/jk/.local/lib/python3.10/site-packages/holoviews/plotting/bokeh/renderer.py", line 70, in get_plot
    plot = super().get_plot(obj, doc, renderer, **kwargs)
  File "/home/jk/.local/lib/python3.10/site-packages/holoviews/plotting/renderer.py", line 236, in get_plot
    plot = self_or_cls.plotting_class(obj)(obj, renderer=renderer,
  File "/home/jk/.local/lib/python3.10/site-packages/holoviews/plotting/bokeh/plot.py", line 690, in __init__
    self.layout, self.subplots, self.paths = self._init_layout(layout)
  File "/home/jk/.local/lib/python3.10/site-packages/holoviews/plotting/bokeh/plot.py", line 702, in _init_layout
    frame_ranges = OrderedDict([(key, self.compute_ranges(layout, key, frame_ranges))
  File "/home/jk/.local/lib/python3.10/site-packages/holoviews/plotting/bokeh/plot.py", line 702, in <listcomp>
    frame_ranges = OrderedDict([(key, self.compute_ranges(layout, key, frame_ranges))
  File "/home/jk/.local/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 595, in compute_ranges
    self._compute_group_range(group, elements, ranges, framewise,
  File "/home/jk/.local/lib/python3.10/site-packages/holoviews/plotting/plot.py", line 705, in _compute_group_range
    data_range = el.range(el_dim, dimension_range=False)
  File "/home/jk/.local/lib/python3.10/site-packages/holoviews/core/data/__init__.py", line 199, in pipelined_fn
    result = method_fn(*args, **kwargs)
  File "/home/jk/.local/lib/python3.10/site-packages/holoviews/core/data/__init__.py", line 508, in range
    lower, upper = self.interface.range(self, dim)
  File "/home/jk/.local/lib/python3.10/site-packages/holoviews/core/data/pandas.py", line 182, in range
    column = column.sort_values()
  File "/home/jk/.local/lib/python3.10/site-packages/pandas/core/series.py", line 3634, in sort_values
    sorted_index = nargsort(values_to_sort, kind, bool(ascending), na_position)
  File "/home/jk/.local/lib/python3.10/site-packages/pandas/core/sorting.py", line 429, in nargsort
    indexer = non_nan_idx[non_nans.argsort(kind=kind)]
TypeError: '>' not supported between instances of 'numpy.ndarray' and 'str'
```

**Comment by benjeffery** [comment]
I've been unable to recreate this one.

**Comment by benjeffery** [comment]
Re-open if you hit this. I've not been able to recreate.
