### ISSUE TITLE
Error when visualising undated tree sequences

### ISSUE THREAD

**Issue by duncanMR** [tskit-dev/tsbrowse#183]
With the current version of tsbrowse, a fatal error is thrown if you try and browse an undated inferred tree sequence. For example:

```python
import tsinfer
import msprime

ts_base = msprime.sim_ancestry(
    100,
    sequence_length=1e6,
    random_seed=2,
    recombination_rate=1e-8,
    model="smc_prime",
    population_size=1e4,
)
ts = msprime.sim_mutations(ts_base, rate=1.29e-8, random_seed=2)
sample_data = tsinfer.SampleData.from_tree_sequence(ts)
inferred_ts = tsinfer.infer(sample_data)
inferred_ts.dump("data/inferred.trees")
```

After preprocessing the tree sequence, this happens:

```
 python -m tsbrowse serve ../tsinfer/data/inferred.tsbrowse
2024-10-01 13:32:04,080 [217640] WARNING  py.warnings: /home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/dask/dataframe/__init__.py:42: FutureWarning:
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)

2024-10-01 13:32:05,341 [217640] INFO     tsbrowse: Starting panel server
2024-10-01 13:32:05,341 [217640] INFO     tsbrowse: Initialising pages
2024-10-01 13:32:05,645 [217640] CRITICAL root: Traceback (most recent call last):
  File "/home/duncan/.pyenv/versions/3.10.9/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/duncan/.pyenv/versions/3.10.9/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/duncan/trees/tsbrowse/tsbrowse/__main__.py", line 138, in <module>
    cli()
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/duncan/trees/tsbrowse/tsbrowse/__main__.py", line 77, in serve
    app_ = app.App(tsm)
  File "/home/duncan/trees/tsbrowse/tsbrowse/app.py", line 49, in __init__
    self.pages = {page.title: page(tsm) for page in pages.PAGES}
  File "/home/duncan/trees/tsbrowse/tsbrowse/app.py", line 49, in <dictcomp>
    self.pages = {page.title: page(tsm) for page in pages.PAGES}
  File "/home/duncan/trees/tsbrowse/tsbrowse/pages/popgen.py", line 79, in __init__
    self.content = pn.Column(one_way_panel)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/panel/layout/base.py", line 363, in __init__
    super().__init__(**params)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/panel/reactive.py", line 635, in __init__
    super().__init__(**params)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/panel/reactive.py", line 125, in __init__
    super().__init__(**params)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/panel/viewable.py", line 704, in __init__
    super().__init__(**params)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/panel/viewable.py", line 543, in __init__
    super().__init__(**params)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/panel/viewable.py", line 302, in __init__
    super().__init__(**params)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/param/parameterized.py", line 4188, in __init__
    refs, deps = self.param._setup_params(**params)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/param/parameterized.py", line 1686, in override_initialization
    ret = fn(self_, *args, **kw)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/param/parameterized.py", line 1976, in _setup_params
    setattr(self, name, resolved)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/param/parameterized.py", line 530, in _f
    return f(self, obj, val)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/panel/viewable.py", line 1160, in __set__
    super().__set__(obj, self._transform_value(val))
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/panel/viewable.py", line 1152, in _transform_value
    val[:] = [
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/panel/viewable.py", line 1153, in <listcomp>
    v if isinstance(v, Viewable) else panel(v)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/panel/pane/base.py", line 86, in panel
    pane = PaneBase.get_pane_type(obj, **kwargs)(obj, **kwargs)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/panel/param.py", line 823, in __init__
    self._replace_pane()
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/panel/param.py", line 891, in _replace_pane
    new_object = self.eval(self.object)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/panel/param.py", line 1106, in eval
    return eval_function_with_deps(ref)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/param/parameterized.py", line 165, in eval_function_with_deps
    return function(*args, **kwargs)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/param/depends.py", line 53, in _depends
    return func(*args, **kw)
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/param/reactive.py", line 594, in wrapped
    return eval_fn()(*combined_args, **combined_kwargs)
  File "/home/duncan/trees/tsbrowse/tsbrowse/pages/popgen.py", line 34, in make_one_way_stats
    branch_statistic = ts.segregating_sites(
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/tskit/trees.py", line 8353, in segregating_sites
    return self.__one_way_sample_set_stat(
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/tskit/trees.py", line 7513, in __one_way_sample_set_stat
    stat = self.__run_windowed_stat(
  File "/home/duncan/trees/tsbrowse/env/lib/python3.10/site-packages/tskit/trees.py", line 7475, in __run_windowed_stat
    stat = method(*args, **kwargs, windows=windows)
_tskit.LibraryError: Statistics using branch lengths cannot be calculated when time_units is 'uncalibrated'. (TSK_ERR_TIME_UNCALIBRATED)


~/trees/tsbrowse on main via env took 3s
1 %
```

In my case, I don't want to run tsdate before visualising it. I'm guessing it should just exclude the stats tab when the time units are uncalibrated?

**Comment by jeromekelleher** [comment]
We're going to remove the stats tab entirely - this is one more motivation for doing so!
